version: "3.8"

services:
    docker-dev:
      image: docker:dind
      container_name: docker-dev
      privileged: true
      volumes:
        - ~/docker/storj/config/vscode/repo/:/repo
      ports:
        - 9003:9001
      network_mode: bridge
#command to run in container terminal to install portainer: docker run -d -p 9003:9001 --name portainer_agent --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes:/var/lib/docker/volumes cr.portainer.io/portainer/agent